### ISSUE TITLE
Bug with back arrow in permissions gui

### ISSUE THREAD

**Issue by JustBru00** [BrannonBlair/FactionsGUI#3]
![2015-09-05_19 56 47](https://cloud.githubusercontent.com/assets/11063799/9701760/57e8fdf6-5408-11e5-9117-b6a07a8a68ad.png)

As you can see in the photo the back arrow itemstack has a -1 amount.

**Comment by JustBru00** [comment]
Also in:
![2015-09-05_20 00 01](https://cloud.githubusercontent.com/assets/11063799/9701765/d34ef7de-5408-11e5-9b40-4d5509b90f1e.png)

**Comment by BrannonBlair** [comment]
It's suppose to. Like, it means back one.
